{
  File generated by GameHelper, tool provided with OGLCScene library.
  Usage:
    - call TLevelTemple.LoadTexture() when you construct your texture atlas.
    - call LoadLevel() to load the current game level.
    - retrieve the world area with property WordArea.
}

unit u_leveltemple;

{$mode ObjFPC}{$H+}

interface

uses
  Classes, SysUtils,
  OGLCScene;

type

{ TLevelTemple }

TLevelTemple = class(TOGLCDecorManager)
private
  class var FAtlas: TOGLCTextureAtlas;
protected
  function ScaleWF(AValue: single): single; override;
  function ScaleHF(AValue: single): single; override;
public
  class procedure LoadTexture(aAtlas: TAtlas);
  procedure BuildLevel(aIndex: integer);
end;

implementation
uses u_app, u_common;

const
Data_LevelTemple='WorldX|0.0000|WorldY|0.0000|WorldWidth|2048.0000|WorldHeight|768.0000|UseSkyGradient|true|SkyX|0.0000|SkyY|0.0000|SkyLayer|11|SkyWidth|1024|SkyHeight|460|SkyGradientData|2 0.000 2 0.000 0080FFFF 1.000 0080FFFF 1.000 2 0.000 800080FF 1.000 800080FF|'+
  'LayerLoopMode|0 0 0 0 0 0 0 0 1 0 1 0|'+
  'SurfaceCount|19|'+
  'S0|L,8,N,Ground1.svg,X,0.0000,Y,421.0000,W,178,H,53|'+
  'S1|L,10,N,GrassBunch1.svg,X,41.8130,Y,286.1572,W,265,H,143|'+
  'S2|L,10,N,GrassBunch1.svg,X,617.7726,Y,286.1572,W,265,H,143,F,1|'+
  'S3|L,10,N,BumpMiddle.svg,X,478.3217,Y,343.1000,W,61,H,80|'+
  'S4|L,10,N,RockRound.svg,X,325.1000,Y,350.3627,W,126,H,71|'+
  'S5|L,10,N,RockRound.svg,X,545.1000,Y,355.8862,W,126,H,71|'+
  'S6|L,10,N,TotemBig.svg,X,719.1000,Y,193.4012,W,78,H,229|'+
  'S7|L,10,N,TotemSmall.svg,X,952.9417,Y,294.0858,W,78,H,135|'+
  'S8|L,10,N,GrassLarge1.svg,X,294.5000,Y,388.6068,W,207,H,33|'+
  'S9|L,10,N,GrassLarge1.svg,X,510.9378,Y,388.6000,W,207,H,33,F,1|'+
  'S10|L,10,N,BumpSmall.svg,X,1042.0735,Y,367.3094,W,43,H,56|'+
  'S11|L,10,N,GrassLarge1.svg,X,846.0327,Y,388.6000,W,207,H,33,F,1|'+
  'S12|L,10,N,TotemBig.svg,X,292.0733,Y,202.9096,W,53,H,212,T,00000064|'+
  'S13|L,8,N,Ground1.svg,X,177.4998,Y,421.0000,W,178,H,53|'+
  'S14|L,8,N,Ground1.svg,X,355.0000,Y,421.0000,W,178,H,53|'+
  'S15|L,8,N,Ground1.svg,X,532.5000,Y,421.0000,W,178,H,53|'+
  'S16|L,8,N,Ground1.svg,X,710.0000,Y,421.0000,W,178,H,53|'+
  'S17|L,8,N,Ground1.svg,X,1064.9999,Y,421.0000,W,178,H,53|'+
  'S18|L,8,N,Ground1.svg,X,887.4999,Y,421.0000,W,178,H,53';

Data_Level2='WorldX|0.0000|WorldY|0.0000|WorldWidth|1024.0000|WorldHeight|768.0000|UseSkyGradient|true|SkyX|0.0000|SkyY|0.0000|SkyLayer|11|SkyWidth|1024|SkyHeight|460|SkyGradientData|2 0.000 2 0.000 00FFFFFF 1.000 00FFFFFF 1.000 2 0.000 800040FF 1.000 800040FF|'+
  'LayerLoopMode|0 0 0 0 0 0 0 0 1 0 2 0|'+
  'SurfaceCount|2|'+
  'S0|L,8,N,Ground1.svg,X,0.0000,Y,421.0000,W,178,H,53|'+
  'S1|L,10,N,BumpSmall.svg,X,601.0447,Y,365.9644,W,43,H,56';

function TLevelTemple.ScaleWF(AValue: single): single;
begin
  Result := u_app.ScaleWF(AValue);
end;

function TLevelTemple.ScaleHF(AValue: single): single;
begin
  Result := u_app.ScaleHF(AValue);
end;
{ TLevelTemple }

class procedure TLevelTemple.LoadTexture(aAtlas: TOGLCTextureAtlas);
var dataFolder: string;
begin
  FAtlas := aAtlas;
  dataFolder := FScene.App.DataFolder;
  aAtlas.AddFromSVG(dataFolder+'Sprites\Temple\GrassBunch1.svg', u_app.ScaleW(265), -1);
  aAtlas.AddFromSVG(dataFolder+'Sprites\Temple\BumpSmall.svg', -1, u_app.ScaleH(56));
  aAtlas.AddFromSVG(dataFolder+'Sprites\Temple\BumpMiddle.svg', -1, u_app.ScaleH(80));
  aAtlas.AddFromSVG(dataFolder+'Sprites\Common\Ground1.svg', u_app.ScaleW(178), -1);
  aAtlas.AddFromSVG(dataFolder+'Sprites\Temple\RockRound.svg', u_app.ScaleW(126), -1);
  aAtlas.AddFromSVG(dataFolder+'Sprites\Temple\GrassLarge1.svg', u_app.ScaleW(207), -1);
  aAtlas.AddFromSVG(dataFolder+'Sprites\Temple\TotemBig.svg', -1, u_app.ScaleH(229));
  aAtlas.AddFromSVG(dataFolder+'Sprites\Temple\TotemSmall.svg', -1, u_app.ScaleH(135));
end;

procedure TLevelTemple.BuildLevel(aIndex: integer);
begin
  case aIndex of
    0: DoBuildLevel(Data_LevelTemple, FAtlas);
    1: DoBuildLevel(Data_Level2, FAtlas);
    else raise exception.create('level index out of bounds');
  end;
end;

end.
